### PR TITLE
Add data validation

### PR DESCRIPTION
**Pull request by sgosline**
creating PR to track this

### CODE REVIEW

**Review by sgosline — COMMENTED** [review]
HI @addymmoran I think this is ok to be merged with a few changes:
1- can you move the schema validation to another script? I'd like to import it and call it from dataQcBmd so we can validate before (and also call independently as a test)
2- allow this script to be run independently

**Comment by addymmoran** [comment]
@sgosline You got it. Just pushed the updates. By "allow this script to be run independently" is it okay to leave it as a function that accepts a dataframe as one of the parameters or were you wanting it to have a main so it can be called using the "python3 validate.py ... "  syntax?

**Comment by sgosline** [comment]
I meant to add a main method as well, so we can call `python3 validate.py` because I hope to incorporate this into unit testing when I get to it.

**Comment by addymmoran** [comment]
Just pushed those updates :)

**Pull request merged**
